const MockData = {
    "code": 0,
    "message": "success",
    "data": {
        "total": 3,
        "list": [
            {
                "id": 18,
                "contentId": 1368,
                "contentType": 1,
                "userId": 196934,
                "businessId": null,
                "viewTime": 133,
                "viewCount": 10,
                "position": null,
                "createTime": 1721721822579,
                "startTime": 1721721821922,
                "lastTime": 1721721821922,
                "type": null,
                "userName": "Freja",
                "videoName": null,
                "unionId": "oDzuQ6rHdkR7RwLHiEl1IPcuq6KQ",
                "openId": "oMQpO41PQlwnQCPvwXzeTEtG-GY8",
                "phone": "18510167273",
                "city": "北京",
                "hospitalName": "仓鼠诊所",
                "profession": "口腔医生",
                "department": "口腔内科",
                "createdAt": 1705908325149,
                "isChecked": 0
            },
            {
                "id": 17,
                "contentId": 1415,
                "contentType": 1,
                "userId": 196934,
                "businessId": null,
                "viewTime": 19,
                "viewCount": 4,
                "position": null,
                "createTime": 1721720088668,
                "startTime": 1721720088653,
                "lastTime": 1721720088653,
                "type": null,
                "userName": "Freja",
                "videoName": null,
                "unionId": "oDzuQ6rHdkR7RwLHiEl1IPcuq6KQ",
                "openId": "oMQpO41PQlwnQCPvwXzeTEtG-GY8",
                "phone": "18510167273",
                "city": "北京",
                "hospitalName": "仓鼠诊所",
                "profession": "口腔医生",
                "department": "口腔内科",
                "createdAt": 1705908325149,
                "isChecked": 0
            },
            {
                "id": 16,
                "contentId": 12,
                "contentType": 1,
                "userId": 164847,
                "businessId": null,
                "viewTime": 160,
                "viewCount": 7,
                "position": null,
                "createTime": 1721616919030,
                "startTime": 1721616918562,
                "lastTime": 1721616918562,
                "type": null,
                "userName": null,
                "videoName": null,
                "unionId": null,
                "openId": null,
                "phone": null,
                "city": null,
                "hospitalName": null,
                "profession": null,
                "department": null,
                "createdAt": null,
                "isChecked": null
            }
        ],
        "pageNum": 0,
        "pageSize": 10,
        "pages": 1,
        "size": 3,
        "result": null
    }
}