/*
 * @Author: Freja
 * @Date: 2024-07-26 15:15:16
 * @FilePath: /gsk-admin/page/wxmaterial/list_mockData.js
 * @LastEditors: Freja
 * @LastEditTime: 2024-07-28 17:17:43
 */
const WxmaterialList_MockData = {
  "status": 1000,
  "data": {
      "total": 254,
      "list": [
          {
              "id": 1415,
              "cateSlug": "yamingan",
              "cateName": "牙敏感",
              "materialType": "gskpost",
              "mediaId": "skyyh-d949b831-a282-4890-8635-bc7c97f7c8d7",
              "itemTitle": "20221107测试",
              "itemDigest": "test",
              "itemThumbMediaId": "",
              "itemThumbUrl": "https://cn01skyyhdevtestsa01.blob.core.chinacloudapi.cn/image/yake/368869cd-7240-4ea4-bf3c-1f4a1e898f1a.png",
              "itemUrl": "/pages/post/postdetail?postid=skyyh-d949b831-a282-4890-8635-bc7c97f7c8d7",
              "itemContentSourceUrl": "",
              "itemCreateTime": 1667803498,
              "itemUpdateTime": 1667803498,
              "itemShowCoverPic": null,
              "itemAuthor": "",
              "isPublished": 1,
              "createdAt": 1667803498034,
              "updatedAt": 1710313044582,
              "htmlContent": "<p>test</p>",
              "updateTimeStr": "2022-11-07 14:44:58",
              "statusName": "已发布",
              "status": 1
          },
          {
              "id": 1367,
              "cateSlug": "jingyingguanli",
              "cateName": "经营管理",
              "materialType": "news",
              "mediaId": "P2Hjz2JJA1lkMW_LfbI_9eEdTg_XUO1VaADWiL8C_cBIYFM4k2s5Pv8OUiw5nAp5",
              "itemTitle": "流量时代，口腔医师该如何自处？——专访苏建宏医师",
              "itemDigest": "● 今日口腔：首先想请您谈一谈，对于开业口腔医师来说必备的素养有哪些？● 苏建宏医师：首先，作为全科口腔医师",
              "itemThumbMediaId": "rPvuTxdP5gDerClYIhxT_qM84jiBRYuG47L_BFjvYTmJR6njFYIiA1M6VL00oQDd",
              "itemThumbUrl": "https://mmbiz.qpic.cn/mmbiz_jpg/pFm10SPQFzqrdphg7k5bUrK0WGzO2ThXMGZPof916SLQVfUmuELOXElZiar68M2BYoT3iceWJnMjeecwMBicBAZ7w/0?wx_fmt=jpeg",
              "itemUrl": "http://mp.weixin.qq.com/s?__biz=MjM5Njk4NTMzMQ==&mid=2247484358&idx=1&sn=659a76a72fedf791b388da57cdf10f4d&chksm=a6e1a35a91962a4cfd8a83280dfb829be9746af1efd31b4563b406fd316a1adca53589cfd7b6#rd",
              "itemContentSourceUrl": "",
              "itemCreateTime": 1667385005,
              "itemUpdateTime": 1667383831,
              "itemShowCoverPic": 0,
              "itemAuthor": "医百科技",
              "isPublished": 1,
              "createdAt": 1667383831000,
              "updatedAt": 1667383831000,
              "htmlContent": "",
              "updateTimeStr": "2022-11-02 18:10:31",
              "statusName": "已发布",
              "status": 1
          },
          {
              "id": 1368,
              "cateSlug": "huanzhejiaoyu-1",
              "cateName": "患者教育-牙敏感",
              "materialType": "news",
              "mediaId": "P2Hjz2JJA1lkMW_LfbI_9dct1VDP-WrCmlh3uwYu86P0lWTg7G4aVEq6B1HYDPFv",
              "itemTitle": "您家里有老人戴假牙吗?",
              "itemDigest": "",
              "itemThumbMediaId": "",
              "itemThumbUrl": "https://cn01skyyhdevtestsa01.blob.core.chinacloudapi.cn/image/yake/65d6cb0a-3cae-4edb-b413-75f1d5de7dba.jpg",
              "itemUrl": "http://mp.weixin.qq.com/s?__biz=MjM5Njk4NTMzMQ==&mid=2247484351&idx=1&sn=e5ef175d68534cd448295aec39b13070&chksm=a6e1a32391962a358ac01ab4be62cbb17f19b1089c9946196b3881496f7ccac7cf49abe9be1b#rd",
              "itemContentSourceUrl": "",
              "itemCreateTime": 1667385005,
              "itemUpdateTime": 1667383728,
              "itemShowCoverPic": 0,
              "itemAuthor": "医百科技",
              "isPublished": 1,
              "createdAt": 1667383728000,
              "updatedAt": 1667383728000,
              "htmlContent": "",
              "updateTimeStr": "2022-11-02 18:08:48",
              "statusName": "已发布",
              "status": 1
          },
          {
              "id": 1369,
              "cateSlug": "huanzhejiaoyu-6",
              "cateName": "患者教育-牙基会合作专区",
              "materialType": "news",
              "mediaId": "P2Hjz2JJA1lkMW_LfbI_9VMUrpuvijRTMohWD_5H95mVOD6FnblRub4dXGFOASki",
              "itemTitle": "口腔医师遇到可疑HIV感染者应如何处理？",
              "itemDigest": "口腔科医师在临床中遇到可疑HIV感染患者，应首先行酶联免疫吸附试验，对患者血液中的HIV抗体进行初步筛查，初",
              "itemThumbMediaId": "",
              "itemThumbUrl": "https://cn01skyyhdevtestsa01.blob.core.chinacloudapi.cn/image/yake/5b369b83-345a-4d5d-8d24-31e061771203.jpg",
              "itemUrl": "http://mp.weixin.qq.com/s?__biz=MjM5Njk4NTMzMQ==&mid=2247484341&idx=1&sn=729c0c8a9fba78ab7f539aeed17c4419&chksm=a6e1a32991962a3faeebcdf172c01f7b85a49b17e50d2121ed26fd4098ec09667fe5a8be73a3#rd",
              "itemContentSourceUrl": "",
              "itemCreateTime": 1667385005,
              "itemUpdateTime": 1667383548,
              "itemShowCoverPic": 0,
              "itemAuthor": "医百科技",
              "isPublished": 1,
              "createdAt": 1667383548000,
              "updatedAt": 1667383548000,
              "htmlContent": "",
              "updateTimeStr": "2022-11-02 18:05:48",
              "statusName": "已发布",
              "status": 1
          },
          {
              "id": 1370,
              "cateSlug": "huanzhejiaoyu-3",
              "cateName": "患者教育-义齿护理",
              "materialType": "news",
              "mediaId": "P2Hjz2JJA1lkMW_LfbI_9Udux5MbLfHqagBMPXpegiMIn0XWqFhfhe4y-A9Y1Ufx",
              "itemTitle": "阻生牙和复杂牙的微创和规范化拔除",
              "itemDigest": "今日口腔 史克牙e汇 2021-02-05 18:20微创拔牙的概念11中华口腔医学会口腔颌面外科专委会牙槽",
              "itemThumbMediaId": "",
              "itemThumbUrl": "https://cn01skyyhdevtestsa01.blob.core.chinacloudapi.cn/image/yake/4c87c9c1-f2a5-47a8-a659-a7ea0b9e8cd4.jpg",
              "itemUrl": "http://mp.weixin.qq.com/s?__biz=MjM5Njk4NTMzMQ==&mid=2247484329&idx=1&sn=88f15fb86775ed0c588cb4e9b4f691e5&chksm=a6e1a33591962a2387da8cc80175100c81560e5045016d17705ace7dcdd4f17420e3c4041876#rd",
              "itemContentSourceUrl": "",
              "itemCreateTime": 1667385005,
              "itemUpdateTime": 1667383231,
              "itemShowCoverPic": 0,
              "itemAuthor": "医百科技",
              "isPublished": 1,
              "createdAt": 1667383231000,
              "updatedAt": 1667383231000,
              "htmlContent": "",
              "updateTimeStr": "2022-11-02 18:00:31",
              "statusName": "已发布",
              "status": 1
          },
          {
              "id": 1371,
              "cateSlug": "kouqiangyufang",
              "cateName": "口腔预防",
              "materialType": "news",
              "mediaId": "P2Hjz2JJA1lkMW_LfbI_9YlyiZe2OvnHMWzWdvTVTof69h5HllOnG8SRzI1jQDC6",
              "itemTitle": "牙龈总“上火”，怎么办？",
              "itemDigest": "在我们的传统观念中，似乎有一种“一切皆是上火”   的说法，比如：口腔溃疡是因为上火；脸上长痘是因为上火，就",
              "itemThumbMediaId": "",
              "itemThumbUrl": "https://cn01skyyhdevtestsa01.blob.core.chinacloudapi.cn/image/yake/363e6a61-2f12-4cfd-9ea4-867491c4201b.jpg",
              "itemUrl": "http://mp.weixin.qq.com/s?__biz=MjM5Njk4NTMzMQ==&mid=2247484322&idx=1&sn=a870fa17480989e1bc08935463f66ee2&chksm=a6e1a33e91962a2808fcb7f9a867254db87db9c52c837818dab0182d443c81c99634bc2a48a3#rd",
              "itemContentSourceUrl": "",
              "itemCreateTime": 1667385005,
              "itemUpdateTime": 1667383125,
              "itemShowCoverPic": 0,
              "itemAuthor": "test",
              "isPublished": 1,
              "createdAt": 1667383125000,
              "updatedAt": 1667383125000,
              "htmlContent": "",
              "updateTimeStr": "2022-11-02 17:58:45",
              "statusName": "已发布",
              "status": 1
          },
          {
              "id": 1372,
              "cateSlug": "yazhoujibing",
              "cateName": "牙周疾病",
              "materialType": "news",
              "mediaId": "P2Hjz2JJA1lkMW_LfbI_9THf4vm0ZW7A62LJO7Oorn1IHEfNcwkhuP_sxYlgnQlN",
              "itemTitle": "所有口腔医生都需要掌握的 – 牙周维护治疗",
              "itemDigest": "菌斑控制是重度牙周炎的患者可以接受复杂的修复治疗，并且保持稳定的前提。菌斑控制分为两个大部分，一是由牙医定期",
              "itemThumbMediaId": "rPvuTxdP5gDerClYIhxT_op44o3YJ0iNsRUPHMAA62rIvNjY7IophQZPb9MXrBfL",
              "itemThumbUrl": "https://cn01skyyhdevtestsa01.blob.core.chinacloudapi.cn/image/yake/1f44ea8d-4489-4ccf-8bb8-e50b209a668f.jpg",
              "itemUrl": "http://mp.weixin.qq.com/s?__biz=MjM5Njk4NTMzMQ==&mid=2247484316&idx=1&sn=c943085e92586255700c9d986ae83355&chksm=a6e1a30091962a1654618140d2104338a6da253d30ffe7f897a805f56bf63da70b5d3d5d9f76#rd",
              "itemContentSourceUrl": "",
              "itemCreateTime": 1667385005,
              "itemUpdateTime": 1667382915,
              "itemShowCoverPic": 0,
              "itemAuthor": "test",
              "isPublished": 1,
              "createdAt": 1667382915000,
              "updatedAt": 1667382915000,
              "htmlContent": "",
              "updateTimeStr": "2022-11-02 17:55:15",
              "statusName": "已发布",
              "status": 1
          },
          {
              "id": 1373,
              "cateSlug": "huanzhejiaoyu-4",
              "cateName": "患者教育-义齿稳固",
              "materialType": "news",
              "mediaId": "P2Hjz2JJA1lkMW_LfbI_9WDz-FEyJ8dyRv0ASt4QdsigEq7-4JPRVOECOeCwj3X0",
              "itemTitle": "牙根纵裂的诊断——刘学军教授",
              "itemDigest": "牙根纵裂的发病率河南省口腔医院特诊科曾做过一项根管治疗疗效回顾研究，研究对象为2010年5月~2016年5月",
              "itemThumbMediaId": "rPvuTxdP5gDerClYIhxT_qM84jiBRYuG47L_BFjvYTmJR6njFYIiA1M6VL00oQDd",
              "itemThumbUrl": "https://mmbiz.qpic.cn/mmbiz_jpg/pFm10SPQFzqrdphg7k5bUrK0WGzO2ThXMGZPof916SLQVfUmuELOXElZiar68M2BYoT3iceWJnMjeecwMBicBAZ7w/0?wx_fmt=jpeg",
              "itemUrl": "http://mp.weixin.qq.com/s?__biz=MjM5Njk4NTMzMQ==&mid=2247484309&idx=1&sn=c5364625abc987aa7feea6e912a256ef&chksm=a6e1a30991962a1f7135c3134af8fe7266a4aaf081a79f8c578e0b27850ab349002356b11531#rd",
              "itemContentSourceUrl": "",
              "itemCreateTime": 1667385005,
              "itemUpdateTime": 1667382845,
              "itemShowCoverPic": 0,
              "itemAuthor": "医百科技",
              "isPublished": 1,
              "createdAt": 1667382845000,
              "updatedAt": 1667382845000,
              "htmlContent": "",
              "updateTimeStr": "2022-11-02 17:54:05",
              "statusName": "已发布",
              "status": 1
          },
          {
              "id": 1374,
              "cateSlug": "kouqiangzhongzhi",
              "cateName": "口腔种植",
              "materialType": "news",
              "mediaId": "P2Hjz2JJA1lkMW_LfbI_9daAQOyxlCh25ZODlRKKUpaVgNAnZ_F20Mrdt4AAKD01",
              "itemTitle": "几张种植术后X线片引发的……",
              "itemDigest": "为提高口腔医疗水平，促口腔行业规范发展，特开辟   “口腔名医随感录”栏目  ，以期作为口腔各学科专家对话基",
              "itemThumbMediaId": "rPvuTxdP5gDerClYIhxT_pg3zce8J74BMD_zRM7oiQj8KDrYFVP6TGHlDT8saHEo",
              "itemThumbUrl": "https://cn01skyyhdevtestsa01.blob.core.chinacloudapi.cn/image/yake/47abdb7c-dfad-496c-866c-fa247348e5ee.jpg",
              "itemUrl": "http://mp.weixin.qq.com/s?__biz=MjM5Njk4NTMzMQ==&mid=2247484297&idx=1&sn=dd71a796dd2ce118dae21dad1e0447d0&chksm=a6e1a31591962a03fde06df2a0ce48d495289b65714beb4a0375930959cee18017234eb7c0ff#rd",
              "itemContentSourceUrl": "",
              "itemCreateTime": 1667385005,
              "itemUpdateTime": 1667382772,
              "itemShowCoverPic": 0,
              "itemAuthor": "医百科技",
              "isPublished": 1,
              "createdAt": 1667382772000,
              "updatedAt": 1667382772000,
              "htmlContent": "",
              "updateTimeStr": "2022-11-02 17:52:52",
              "statusName": "已发布",
              "status": 1
          },
          {
              "id": 1375,
              "cateSlug": "huanzhejiaoyu-5",
              "cateName": "患者教育-常规口腔患教",
              "materialType": "news",
              "mediaId": "P2Hjz2JJA1lkMW_LfbI_9QkL6u5jTQ4syeIqXPXo6L6yR3j0oxvJiVjhSSMVuuhD",
              "itemTitle": "根管治疗诊间疼痛的原因与对策——姬爱平主任医师",
              "itemDigest": "根管治疗诊间疼痛是根管治疗术的常见并发症，绝大多数病例可在预期的诊疗期内缓解消失，少数病例持续时间较长，甚至",
              "itemThumbMediaId": "rPvuTxdP5gDerClYIhxT_io7TAcKVg8y4FhrnZMZYfZMZ2zZ0l_QBx0hZzDycyAW",
              "itemThumbUrl": "https://mmbiz.qpic.cn/mmbiz_jpg/pFm10SPQFzqrdphg7k5bUrK0WGzO2ThXjM9rGvic6JB0PRlcLjEfxdWnt0MR27GYFp9V90TP4ByZE9x6d2HNX8g/0?wx_fmt=jpeg",
              "itemUrl": "http://mp.weixin.qq.com/s?__biz=MjM5Njk4NTMzMQ==&mid=2247484290&idx=1&sn=4d405129ae71610ca0310b118b4fee61&chksm=a6e1a31e91962a085e061a4ed2ab5766317c13762a1ddf20f388c178078210e74af531f4647b#rd",
              "itemContentSourceUrl": "",
              "itemCreateTime": 1667385005,
              "itemUpdateTime": 1667382670,
              "itemShowCoverPic": 0,
              "itemAuthor": "医百科技",
              "isPublished": 1,
              "createdAt": 1667382670000,
              "updatedAt": 1667382670000,
              "htmlContent": "",
              "updateTimeStr": "2022-11-02 17:51:10",
              "statusName": "已发布",
              "status": 1
          }
      ],
      "pageNum": 1,
      "pageSize": 10,
      "size": 10,
      "startRow": 1,
      "endRow": 10,
      "pages": 26,
      "prePage": 0,
      "nextPage": 2,
      "isFirstPage": true,
      "isLastPage": false,
      "hasPreviousPage": false,
      "hasNextPage": true,
      "navigatePages": 8,
      "navigatepageNums": [
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8
      ],
      "navigateFirstPage": 1,
      "navigateLastPage": 8
  }
}

const CategoryBaseList_MockData = {
    "code": 0,
    "message": "success",
    "data": [
        {
            "id": "1",
            "companyId": 1,
            "type": 2,
            "categoryType": 1,
            "createTime": 1721292034000,
            "updateTime": 1721292034000,
            "name": "产品",
            "parentId": null,
            "isDelete": 0,
            "pageNum": 1,
            "pageSize": 10,
            "list": [
                {
                    "id": "4",
                    "companyId": 1,
                    "type": 2,
                    "categoryType": 2,
                    "createTime": null,
                    "updateTime": null,
                    "name": "保丽净正畸清洁片",
                    "parentId": 1,
                    "isDelete": 0,
                    "pageNum": 1,
                    "pageSize": 10,
                    "list": null
                },
                {
                    "id": "3",
                    "companyId": 1,
                    "type": 2,
                    "categoryType": 2,
                    "createTime": null,
                    "updateTime": null,
                    "name": "保丽净义齿清洁片",
                    "parentId": 1,
                    "isDelete": 0,
                    "pageNum": 1,
                    "pageSize": 10,
                    "list": null
                },
                {
                    "id": "5",
                    "companyId": 1,
                    "type": 2,
                    "categoryType": 2,
                    "createTime": null,
                    "updateTime": null,
                    "name": "保丽净稳固剂",
                    "parentId": 1,
                    "isDelete": 0,
                    "pageNum": 1,
                    "pageSize": 10,
                    "list": null
                },
                {
                    "id": "6",
                    "companyId": 1,
                    "type": 2,
                    "categoryType": 2,
                    "createTime": null,
                    "updateTime": null,
                    "name": "舒适达牙膏",
                    "parentId": 1,
                    "isDelete": 0,
                    "pageNum": 1,
                    "pageSize": 10,
                    "list": null
                },
                {
                    "id": "7",
                    "companyId": 1,
                    "type": 2,
                    "categoryType": 2,
                    "createTime": null,
                    "updateTime": null,
                    "name": "无品牌",
                    "parentId": 1,
                    "isDelete": 0,
                    "pageNum": 1,
                    "pageSize": 10,
                    "list": null
                }
            ]
        },
        {
            "id": "2",
            "companyId": 1,
            "type": 1,
            "categoryType": 1,
            "createTime": null,
            "updateTime": null,
            "name": "品牌",
            "parentId": null,
            "isDelete": 0,
            "pageNum": 1,
            "pageSize": 10,
            "list": [
                {
                    "id": "8",
                    "companyId": 1,
                    "type": 2,
                    "categoryType": 2,
                    "createTime": null,
                    "updateTime": null,
                    "name": "保丽净",
                    "parentId": 2,
                    "isDelete": 0,
                    "pageNum": 1,
                    "pageSize": 10,
                    "list": null
                },
                {
                    "id": "9",
                    "companyId": 1,
                    "type": 2,
                    "categoryType": 2,
                    "createTime": null,
                    "updateTime": null,
                    "name": "舒适达",
                    "parentId": 2,
                    "isDelete": 0,
                    "pageNum": 1,
                    "pageSize": 10,
                    "list": null
                },
                {
                    "id": "10",
                    "companyId": 1,
                    "type": 2,
                    "categoryType": 2,
                    "createTime": null,
                    "updateTime": null,
                    "name": "无品牌",
                    "parentId": 2,
                    "isDelete": 0,
                    "pageNum": 1,
                    "pageSize": 10,
                    "list": null
                }
            ]
        },
        {
            "id": "13",
            "companyId": 1,
            "type": 1,
            "categoryType": 1,
            "createTime": null,
            "updateTime": null,
            "name": "用途",
            "parentId": null,
            "isDelete": 0,
            "pageNum": 1,
            "pageSize": 10,
            "list": [
                {
                    "id": "14",
                    "companyId": 1,
                    "type": 1,
                    "categoryType": 2,
                    "createTime": null,
                    "updateTime": null,
                    "name": "HT",
                    "parentId": 13,
                    "isDelete": 0,
                    "pageNum": 1,
                    "pageSize": 10,
                    "list": null
                },
                {
                    "id": "15",
                    "companyId": 1,
                    "type": 1,
                    "categoryType": 2,
                    "createTime": null,
                    "updateTime": null,
                    "name": "问候拜访",
                    "parentId": 13,
                    "isDelete": 0,
                    "pageNum": 1,
                    "pageSize": 10,
                    "list": null
                },
                {
                    "id": "16",
                    "companyId": 1,
                    "type": 1,
                    "categoryType": 2,
                    "createTime": null,
                    "updateTime": null,
                    "name": "专业拜访",
                    "parentId": 13,
                    "isDelete": 0,
                    "pageNum": 1,
                    "pageSize": 10,
                    "list": null
                },
                {
                    "id": "17",
                    "companyId": 1,
                    "type": 1,
                    "categoryType": 2,
                    "createTime": null,
                    "updateTime": null,
                    "name": "其他",
                    "parentId": 13,
                    "isDelete": 0,
                    "pageNum": 1,
                    "pageSize": 10,
                    "list": null
                }
            ]
        },
        {
            "id": "11",
            "companyId": 1,
            "type": 2,
            "categoryType": 1,
            "createTime": null,
            "updateTime": null,
            "name": "品类",
            "parentId": null,
            "isDelete": 0,
            "pageNum": 1,
            "pageSize": 10,
            "list": [
                {
                    "id": "12",
                    "companyId": 1,
                    "type": 2,
                    "categoryType": 2,
                    "createTime": null,
                    "updateTime": null,
                    "name": "口腔",
                    "parentId": 11,
                    "isDelete": 0,
                    "pageNum": 1,
                    "pageSize": 10,
                    "list": null
                }
            ]
        },
        {
            "id": "18",
            "companyId": 1,
            "type": 1,
            "categoryType": 1,
            "createTime": null,
            "updateTime": null,
            "name": "分类",
            "parentId": null,
            "isDelete": 0,
            "pageNum": 1,
            "pageSize": 10,
            "list": [
                {
                    "id": "19",
                    "companyId": 1,
                    "type": 1,
                    "categoryType": 2,
                    "createTime": null,
                    "updateTime": null,
                    "name": "广告",
                    "parentId": 18,
                    "isDelete": 0,
                    "pageNum": 1,
                    "pageSize": 10,
                    "list": null
                },
                {
                    "id": "20",
                    "companyId": 1,
                    "type": 1,
                    "categoryType": 2,
                    "createTime": null,
                    "updateTime": null,
                    "name": "科普",
                    "parentId": 18,
                    "isDelete": 0,
                    "pageNum": 1,
                    "pageSize": 10,
                    "list": null
                },
                {
                    "id": "21",
                    "companyId": 1,
                    "type": 1,
                    "categoryType": 2,
                    "createTime": null,
                    "updateTime": null,
                    "name": "医学专业内容",
                    "parentId": 18,
                    "isDelete": 0,
                    "pageNum": 1,
                    "pageSize": 10,
                    "list": null
                },
                {
                    "id": "22",
                    "companyId": 1,
                    "type": 1,
                    "categoryType": 2,
                    "createTime": null,
                    "updateTime": null,
                    "name": "问候拜访资料",
                    "parentId": 18,
                    "isDelete": 0,
                    "pageNum": 1,
                    "pageSize": 10,
                    "list": null
                }
            ]
        },
        {
            "id": "23",
            "companyId": 1,
            "type": 1,
            "categoryType": 1,
            "createTime": null,
            "updateTime": null,
            "name": "资料类型",
            "parentId": null,
            "isDelete": 0,
            "pageNum": 1,
            "pageSize": 10,
            "list": [
                {
                    "id": "24",
                    "companyId": 1,
                    "type": 1,
                    "categoryType": 2,
                    "createTime": null,
                    "updateTime": null,
                    "name": "H5图文",
                    "parentId": 23,
                    "isDelete": 0,
                    "pageNum": 1,
                    "pageSize": 10,
                    "list": null
                },
                {
                    "id": "25",
                    "companyId": 1,
                    "type": 1,
                    "categoryType": 2,
                    "createTime": null,
                    "updateTime": null,
                    "name": "PDF",
                    "parentId": 23,
                    "isDelete": 0,
                    "pageNum": 1,
                    "pageSize": 10,
                    "list": null
                },
                {
                    "id": "26",
                    "companyId": 1,
                    "type": 1,
                    "categoryType": 2,
                    "createTime": null,
                    "updateTime": null,
                    "name": "视频",
                    "parentId": 23,
                    "isDelete": 0,
                    "pageNum": 1,
                    "pageSize": 10,
                    "list": null
                },
                {
                    "id": "27",
                    "companyId": 1,
                    "type": 1,
                    "categoryType": 2,
                    "createTime": null,
                    "updateTime": null,
                    "name": "外链",
                    "parentId": 23,
                    "isDelete": 0,
                    "pageNum": 1,
                    "pageSize": 10,
                    "list": null
                },
                {
                    "id": "28",
                    "companyId": 1,
                    "type": 1,
                    "categoryType": 2,
                    "createTime": null,
                    "updateTime": null,
                    "name": "PPT",
                    "parentId": 23,
                    "isDelete": 0,
                    "pageNum": 1,
                    "pageSize": 10,
                    "list": null
                },
                {
                    "id": "29",
                    "companyId": 1,
                    "type": 1,
                    "categoryType": 2,
                    "createTime": null,
                    "updateTime": null,
                    "name": "第三方外链",
                    "parentId": 23,
                    "isDelete": 0,
                    "pageNum": 1,
                    "pageSize": 10,
                    "list": null
                }
            ]
        }
    ]
}

const CategoryActivityGetInfo_MockData = {
    "code": 0,
    "message": "success",
    "data": {
        "id": "8",
        "createTime": 1722155016000,
        "updateTime": 1722158213000,
        "contentId": 1415,
        "contentType": 1,
        "activityName": "20221107测试",
        "businessId": null,
        "isDelete": 0,
        "list": [
            {
                "id": "48",
                "createTime": null,
                "categoryActivityId": 8,
                "categoryName": "保丽净正畸清洁片",
                "categoryId": 4,
                "categoryParentId": 1,
                "categoryParentName": "产品",
                "categoryNameList": null
            },
            {
                "id": "49",
                "createTime": null,
                "categoryActivityId": 8,
                "categoryName": "保丽净义齿清洁片",
                "categoryId": 3,
                "categoryParentId": 1,
                "categoryParentName": "产品",
                "categoryNameList": null
            },
            {
                "id": "50",
                "createTime": null,
                "categoryActivityId": 8,
                "categoryName": "保丽净稳固剂",
                "categoryId": 5,
                "categoryParentId": 1,
                "categoryParentName": "产品",
                "categoryNameList": null
            },
            {
                "id": "51",
                "createTime": null,
                "categoryActivityId": 8,
                "categoryName": "舒适达牙膏",
                "categoryId": 6,
                "categoryParentId": 1,
                "categoryParentName": "产品",
                "categoryNameList": null
            },
            {
                "id": "52",
                "createTime": null,
                "categoryActivityId": 8,
                "categoryName": "无品牌",
                "categoryId": 7,
                "categoryParentId": 1,
                "categoryParentName": "产品",
                "categoryNameList": null
            },
            {
                "id": "53",
                "createTime": null,
                "categoryActivityId": 8,
                "categoryName": "保丽净",
                "categoryId": 8,
                "categoryParentId": 2,
                "categoryParentName": "品牌",
                "categoryNameList": null
            },
            {
                "id": "54",
                "createTime": null,
                "categoryActivityId": 8,
                "categoryName": "无品牌",
                "categoryId": 10,
                "categoryParentId": 2,
                "categoryParentName": "品牌",
                "categoryNameList": null
            },
            {
                "id": "55",
                "createTime": null,
                "categoryActivityId": 8,
                "categoryName": "专业拜访",
                "categoryId": 16,
                "categoryParentId": 13,
                "categoryParentName": "用途",
                "categoryNameList": null
            },
            {
                "id": "56",
                "createTime": null,
                "categoryActivityId": 8,
                "categoryName": "口腔",
                "categoryId": 12,
                "categoryParentId": 11,
                "categoryParentName": "品类",
                "categoryNameList": null
            },
            {
                "id": "57",
                "createTime": null,
                "categoryActivityId": 8,
                "categoryName": "问候拜访资料",
                "categoryId": 22,
                "categoryParentId": 18,
                "categoryParentName": "分类",
                "categoryNameList": null
            },
            {
                "id": "58",
                "createTime": null,
                "categoryActivityId": 8,
                "categoryName": "外链",
                "categoryId": 27,
                "categoryParentId": 23,
                "categoryParentName": "资料类型",
                "categoryNameList": null
            }
        ]
    }
}