name: Sync from GitLab to GitHub

on:
  workflow_dispatch:  # 手动触发
    inputs:
      gitlab_repo_url:
        description: 'The GitLab repository URL to pull from'
        required: true
      gitlab_token:
        description: 'The GitLab personal access token'
        required: true
      branch:
        description: 'The branch to sync'
        default: 'azure-test'
        required: true

permissions:  # 添加权限设置
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitLab repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.gitlab_repo_url }}
        ref: ${{ github.event.inputs.branch }}
        token: ${{ github.event.inputs.gitlab_token }}

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Add GitHub remote
      run: git remote add github https://github.com/${{ github.repository }}

    - name: Push to GitHub
      run: |
        git push github ${{ github.event.inputs.branch }} --force
