name: Sync with GitLab

on:
  workflow_dispatch:  # 手动触发
    inputs:
      gitlab_repo_url:
        description: 'The GitLab repository URL to sync with'
        required: true
      gitlab_token:
        description: 'The GitLab personal access token'
        required: true
      branch:
        description: 'The branch to sync'
        default: 'azure-test'
        required: true

permissions:  # 添加权限设置
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v2

    - name: Create or checkout branch
      run: |
        git fetch origin
        git checkout -b ${{ github.event.inputs.branch }} || git checkout ${{ github.event.inputs.branch }}
        git pull origin ${{ github.event.inputs.branch }}
        git push origin ${{ github.event.inputs.branch }}
    
    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Add GitLab remote
      run: git remote add gitlab ${{ github.event.inputs.gitlab_repo_url }}

    - name: Push to GitLab
      env:
        GITLAB_TOKEN: ${{ github.event.inputs.gitlab_token }}
      run: |
        git push --force https://${GITLAB_TOKEN}@${{ github.event.inputs.gitlab_repo_url }} HEAD:${{ github.event.inputs.branch }}
